### ISSUE TITLE
Exclude rule

### ISSUE THREAD

**Issue by Wadzio** [mohamedelhabib/vsts-changed-files-multibranch#1]
Is it possible to exclude some file(s) from Rules?
For example I want to track changes all files but without changes to one file readme.md

```
rules: |
    [Changed]
    src/projectA/**
    !src/projectA/readme.md
```

**Comment by mohamedelhabib** [comment]
Hi @Wadzio

exclusion is added into the 2.3.0. let me know. if this match your usage ?

this is the list of changes https://github.com/mohamedelhabib/vsts-changed-files-multibranch/compare/v2.2.2...v2.3.0

Br
